steps:

- name: 'gcr.io/cloud-builder/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/lamp-stack:${BUILD_ID}']
- name: 'gcr.io/cloud-builder/docker'  
  args: ['push', 'gcr.io/${PROJECT_ID}/lamp-stack:${BUILD_ID}']
