steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ris-kube-dev/lamp-stack:${BUILD_ID}', .]
- name: 'gcr.io/cloud-builders/docker'  
  args: ['push', 'gcr.io/ris-kube-dev/lamp-stack:${BUILD_ID}']
